version: '3'
services:
  webserver:
    image: maxacarvalho/docker-for-nginx
    volumes:
      - ./app:/app/:cached
      - ./logs/webserver/:/var/log/nginx/:cached
      # include the Nginx config necessary for your
      #- ./app/docker/magento/nginx-site.conf:/etc/nginx/conf.d/default.conf
    working_dir: /app/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
  app:
    build:
      context: docker/app/70
      dockerfile: Dockerfile
    volumes:
      - ./app:/app/:cached
      - ./app/docker/magento/local.xml:/public_html/app/etc/local.xml
      - ./logs/app/:/usr/local/var/log/:cached
      # include any extra php config file (.ini)
      #- ./docker/conf/php/app.ini:/usr/local/etc/php/conf.d/zzz-app.ini
    working_dir: /app/
    environment:
      WWWUSER: "${WWWUSER}"
      XDEBUG_HOST: "${XDEBUG_HOST}"
    depends_on:
      - db
      - cache
  node:
    build:
      context: ./docker/images/node
      dockerfile: Dockerfile
      args:
        uid: "${WWWUSER}"
    user: node
    volumes:
      - ./app:/app
  cache:
    image: redis:alpine
    volumes:
      - cache_data:/data
    ports:
      - "6379:6379"
  db:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql/:cached
volumes:
  db_data: {}
  cache_data: {}