version: '3'
services:
  webserver:
    image: maxacarvalho/docker-for-nginx
    volumes:
      - ./app:/public_html/:cached
      - ./app/docker/magento/nginx-site.conf:/etc/nginx/conf.d/default.conf
      - ./logs/webserver/:/var/log/nginx/:cached
    working_dir: /public_html/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    logging:
      driver: "json-file"
      options:
        max-size: 100k
  app:
    image: maxacarvalho/docker-for-php:5.6-fpm
    volumes:
      - ./app:/public_html/:cached
      - ./app/docker/magento/local.xml:/public_html/app/etc/local.xml
      - ./logs/app/:/usr/local/var/log/:cached
#      - ./docker/conf/php/app.ini:/usr/local/etc/php/conf.d/zzz-app.ini
    working_dir: /public_html/
    environment:
      WWWUSER: "${WWWUSER}"
      XDEBUG_HOST: "${XDEBUG_HOST}"
    depends_on:
      - db
      - cache
    logging:
      driver: "json-file"
      options:
        max-size: 100k
  node:
    build:
      context: ./docker/images/node
      dockerfile: Dockerfile
      args:
        uid: "${WWWUSER}"
    user: node
    volumes:
      - ./app:/var/www/html
  cache:
    image: redis:alpine
    volumes:
      - cache_data:/data
    ports:
      - "6379:6379"
  db:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql/:cached
volumes:
  db_data: {}
  cache_data: {}