#!/usr/bin/env bash

docker build \
    -t maxacarvalho/docker-for-php:5.6-fpm \
    -f 5.6/Dockerfile .

docker build \
    -t maxacarvalho/docker-for-php:7.0-fpm \
    -f 7.0/Dockerfile .

docker build \
    -t maxacarvalho/docker-for-php:7.1-fpm \
    -f 7.1/Dockerfile .

docker build \
    -t maxacarvalho/docker-for-php:7.2-fpm \
    -f 7.2/Dockerfile .