#!/bin/sh
set -e

if [ ! -z "$WWWUSER" ]; then
    sed -i "s/user\ \=.*/user\ \= $WWWUSER/g" /usr/local/etc/php-fpm.d/www.conf
    usermod -u $WWWUSER magedocker
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi
chmod -R ugo+rw /.composer

if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi

if [ $# -gt 0 ];then
    exec gosu $WWWUSER "$@"
else
    exec "$@"
fi