FROM node:latest

LABEL maintainer="Max Carvalho <max.carvalho@cloverbox.com.br>"

RUN set -x \
    && apt-get update && apt-get install -y --no-install-recommends autoconf libtool pkg-config nasm build-essential