#!/bin/sh
set -e

if [ ! -z "$WWWUSER" ]; then
    sed -i "s/user\ \=.*/user\ \= $WWWUSER/g" /usr/local/etc/php-fpm.d/www.conf

    # Set UID of user "theuser"
    usermod -u $WWWUSER theuser
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi
chmod -R ugo+rw /.composer

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi

exec gosu $WWWUSER "$@"